/**************************************************************************

    AVStream Simulated Hardware Sample

    Copyright (c) 2001, Microsoft Corporation.

    File:

        hwsim.cpp

    Abstract:
        
        This file contains the hardware simulation.  It fakes "DMA" transfers,
        scatter gather mapping handling, ISR's, etc...  The ISR routine in
        here will be called when an ISR would be generated by the fake hardware
        and it will directly call into the device level ISR for more accurate
        simulation.

    History:

        created 3/9/2001

**************************************************************************/

#include "avshws.h"

/*************************************************/
KDEFERRED_ROUTINE SimulatedInterrupt;
static const LONGLONG kClientHeartbeatTimeout100ns = 20000000LL;
static const ULONG kScatterGatherEntryTag = 'nEGS';

namespace
{
    const UCHAR kPlaceholderBlue = 217;
    const UCHAR kPlaceholderGreen = 26;
    const UCHAR kPlaceholderRed = 13;

    const UCHAR kPlaceholderTextBlue = 64;
    const UCHAR kPlaceholderTextGreen = 255;
    const UCHAR kPlaceholderTextRed = 38;

    const UCHAR kFontP[16][16] = {
        {0,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0},
        {0,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,1,1,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,1,1,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0},
        {0,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0},
        {0,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}
    };

    const UCHAR kFontC[16][16] = {
        {0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0},
        {0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0},
        {0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,0},
        {0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0},
        {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}
    };

    void FillPlaceholderFrameRgb24(
        _Out_writes_bytes_(imageSize) PUCHAR buffer,
        ULONG width,
        ULONG height,
        ULONG imageSize)
    {
        if (!buffer || width == 0 || height == 0) {
            return;
        }

        RtlZeroMemory(buffer, imageSize);

        const ULONG stride = width * 3;
        for (ULONG y = 0; y < height; ++y) {
            UCHAR* row = buffer + (stride * y);
            const ULONG scanlineTint = (y & 1) ? 10 : 0;

            for (ULONG x = 0; x < width; ++x) {
                const ULONG pixel = x * 3;
                row[pixel + 0] = static_cast<UCHAR>(kPlaceholderBlue - scanlineTint);
                row[pixel + 1] = static_cast<UCHAR>(kPlaceholderGreen + (scanlineTint / 3));
                row[pixel + 2] = static_cast<UCHAR>(kPlaceholderRed + (scanlineTint / 4));
            }
        }

        ULONG glyphScale = height / 40;
        if ((width / 80) < glyphScale) {
            glyphScale = width / 80;
        }
        if (glyphScale < 2) {
            glyphScale = 2;
        }
        const ULONG glyphWidth = 16 * glyphScale;
        const ULONG glyphHeight = 16 * glyphScale;
        const ULONG glyphGap = 6 * glyphScale;
        ULONG marginX = width / 16;
        ULONG marginY = height / 14;
        if (marginX < 12) {
            marginX = 12;
        }
        if (marginY < 12) {
            marginY = 12;
        }
        const ULONG totalWidth = (2 * glyphWidth) + glyphGap;

        if (glyphWidth == 0 || glyphHeight == 0 || totalWidth >= width || glyphHeight >= height) {
            return;
        }

        const ULONG originX = width - marginX - totalWidth;
        const ULONG originY = marginY;

        for (ULONG py = 0; py < glyphHeight; ++py) {
            ULONG fontY = py / glyphScale;
            if (fontY > 15) {
                fontY = 15;
            }
            const ULONG rowY = originY + py;
            if (rowY >= height) {
                break;
            }

            for (ULONG px = 0; px < totalWidth; ++px) {
                ULONG fontX = 0;
                BOOLEAN drawPixel = FALSE;

                if (px < glyphWidth) {
                    fontX = px / glyphScale;
                    if (fontX > 15) {
                        fontX = 15;
                    }
                    drawPixel = (kFontP[fontY][fontX] != 0);
                } else if (px >= (glyphWidth + glyphGap)) {
                    fontX = (px - glyphWidth - glyphGap) / glyphScale;
                    if (fontX > 15) {
                        fontX = 15;
                    }
                    drawPixel = (kFontC[fontY][fontX] != 0);
                }

                if (!drawPixel) {
                    continue;
                }

                const ULONG rowX = originX + px;
                if (rowX >= width) {
                    continue;
                }

                UCHAR* pixel = buffer + (rowY * stride) + (rowX * 3);
                pixel[0] = kPlaceholderTextBlue;
                pixel[1] = kPlaceholderTextGreen;
                pixel[2] = kPlaceholderTextRed;
            }
        }
    }
}

void
SimulatedInterrupt (
    IN PKDPC Dpc,
    IN PVOID DeferredContext,
    IN PVOID SystemArg1,
    IN PVOID SystemArg2
    )
{
    CHardwareSimulation* HardwareSim = (CHardwareSimulation*)DeferredContext;
    
    if (HardwareSim)
    {
        HardwareSim -> FakeHardware ();
    }
}


/**************************************************************************

    PAGEABLE CODE

**************************************************************************/

#ifdef ALLOC_PRAGMA
#pragma code_seg("PAGE")
#endif // ALLOC_PRAGMA



CHardwareSimulation::
CHardwareSimulation (
    IN IHardwareSink *HardwareSink
    ) :
    m_HardwareSink (HardwareSink),
    m_ScatterGatherMappingsMax (SCATTER_GATHER_MAPPINGS_MAX),
    m_ScatterGatherLookasideInitialized (FALSE)

/*++

Routine Description:

    Construct a hardware simulation

Arguments:

    HardwareSink -
        The hardware sink interface.  This is used to trigger
        fake interrupt service routines from.

Return Value:

    Success / Failure

--*/

{

    PAGED_CODE();

    //
    // Initialize the DPC's, timer's, and locks necessary to simulate
    // this capture hardware.
    //
    KeInitializeDpc (
        &m_IsrFakeDpc, 
        SimulatedInterrupt, 
        this
        );

    KeInitializeEvent (
        &m_HardwareEvent,
        SynchronizationEvent,
        FALSE
        );

    KeInitializeTimer (&m_IsrTimer);

    KeInitializeSpinLock (&m_ListLock);
    KeInitializeSpinLock (&m_FrameLock);
    NTSTATUS LookasideStatus = ExInitializeLookasideListEx(
        &m_ScatterGatherLookaside,
        NULL,
        NULL,
        NonPagedPoolNx,
        0,
        sizeof(SCATTER_GATHER_ENTRY),
        kScatterGatherEntryTag,
        0);
    if (NT_SUCCESS(LookasideStatus)) {
        m_ScatterGatherLookasideInitialized = TRUE;
    }

}

CHardwareSimulation::
~CHardwareSimulation (
    )
{
    if (m_HardwareState != HardwareStopped ||
        m_SynthesisBuffer ||
        m_TemporaryBuffer ||
        m_DefaultFrameBuffer ||
        m_ClientRequestEvent ||
        m_ScatterGatherMappingsQueued) {
        (void)Stop ();
    }

    if (m_ScatterGatherLookasideInitialized) {
        ExDeleteLookasideListEx(&m_ScatterGatherLookaside);
    }
}

/*************************************************/


CHardwareSimulation *
CHardwareSimulation::
Initialize (
    IN KSOBJECT_BAG Bag,
    IN IHardwareSink *HardwareSink
    )

/*++

Routine Description:

    Initialize the hardware simulation

Arguments:

    HardwareSink -
        The hardware sink interface.  This is what ISR's will be
        triggered through.

Return Value:

    A fully initialized hardware simulation or NULL if the simulation
    could not be initialized.

--*/

{

    PAGED_CODE();

    CHardwareSimulation *HwSim = 
        new (NonPagedPoolNx, 'miSH') CHardwareSimulation (HardwareSink);

    return HwSim;

}

/*************************************************/


NTSTATUS
CHardwareSimulation::
Start (
    IN CImageSynthesizer *ImageSynth,
    IN LONGLONG TimePerFrame,
    IN ULONG Width,
    IN ULONG Height,
    IN ULONG ImageSize
    )

/*++

Routine Description:

    Start the hardware simulation.  This will kick the interrupts on,
    begin issuing DPC's, filling in capture information, etc...
    We keep track of starvation starting at this point.

Arguments:

    ImageSynth -
        The image synthesizer to use to generate pictures to display
        on the capture buffer.

    TimePerFrame -
        The time per frame...  we issue interrupts this often.

    Width -
        The image width

    Height -
        The image height

    ImageSize - 
        The size of the image.  We allocate a temporary scratch buffer
        based on this size to fake hardware.

Return Value:

    Success / Failure (typical failure will be out of memory on the 
    scratch buffer, etc...)

--*/

{

    PAGED_CODE();

    NTSTATUS Status = STATUS_SUCCESS;

    m_ImageSynth = ImageSynth;
    m_TimePerFrame = TimePerFrame;
    m_ImageSize = ImageSize;
    m_Height = Height;
    m_Width = Width;

    InitializeListHead (&m_ScatterGatherMappings);
    m_NumMappingsCompleted = 0;
    m_ScatterGatherMappingsQueued = 0;
    m_NumFramesSkipped = 0;
    m_InterruptTime = 0;

    KeQuerySystemTimePrecise (&m_StartTime);

    //
    // Allocate a scratch buffer for the synthesizer.
    //
    m_SynthesisBuffer = reinterpret_cast <PUCHAR> (
        ExAllocatePool2 (
            POOL_FLAG_NON_PAGED,
            m_ImageSize,
            AVSHWS_POOLTAG
            )
        );

    if (!m_SynthesisBuffer) {
        Status = STATUS_INSUFFICIENT_RESOURCES;
    }

	//
	// Allocate a temporary frame buffer;
	//
	m_TemporaryBuffer = reinterpret_cast <PUCHAR> (
		ExAllocatePool2(
			POOL_FLAG_NON_PAGED,
			m_ImageSize,
			AVSHWS_POOLTAG
			)
		);

	if (!m_TemporaryBuffer) {
		Status = STATUS_INSUFFICIENT_RESOURCES;
	}

    m_DefaultFrameBuffer = reinterpret_cast<PUCHAR>(
        ExAllocatePool2(
            POOL_FLAG_NON_PAGED,
            m_ImageSize,
            AVSHWS_POOLTAG));
    if (!m_DefaultFrameBuffer) {
        Status = STATUS_INSUFFICIENT_RESOURCES;
    } else {
        if (m_ImageSynth && m_ImageSynth->GetBytesPerPixel() == 3) {
            FillPlaceholderFrameRgb24(m_DefaultFrameBuffer, m_Width, m_Height, m_ImageSize);
        }
    }

    if (NT_SUCCESS(Status) && !m_ClientRequestEventObject) {
        UNICODE_STRING eventName;
        RtlInitUnicodeString(&eventName, L"\\BaseNamedObjects\\VirtuaCamClientRequest");
        m_ClientRequestEventObject = IoCreateNotificationEvent(&eventName, &m_ClientRequestEvent);
        if (!m_ClientRequestEventObject) {
            Status = STATUS_INSUFFICIENT_RESOURCES;
        } else {
            ObReferenceObject(m_ClientRequestEventObject);
            ZwClose(m_ClientRequestEvent);
            m_ClientRequestEvent = NULL;
            KeClearEvent(m_ClientRequestEventObject);
        }
    }

    //
    // If everything is ok, start issuing interrupts.
    //
    if (NT_SUCCESS (Status)) {
        KIRQL irql;
        KeAcquireSpinLock(&m_FrameLock, &irql);
        m_ClientConnected = FALSE;
        m_LastFrameTime.QuadPart = 0;
        KeReleaseSpinLock(&m_FrameLock, irql);

        //
        // Set up the synthesizer with the width, height, and scratch buffer.
        //
        m_ImageSynth -> SetImageSize (m_Width, m_Height);
        m_ImageSynth -> SetBuffer (m_SynthesisBuffer);

        LARGE_INTEGER NextTime;
        NextTime.QuadPart = m_StartTime.QuadPart + m_TimePerFrame;

        m_HardwareState = HardwareRunning;
        KeSetTimer (&m_IsrTimer, NextTime, &m_IsrFakeDpc);

    }
    else {
        if (m_ClientRequestEvent) {
            ZwClose(m_ClientRequestEvent);
            m_ClientRequestEvent = NULL;
        }
        if (m_ClientRequestEventObject) {
            ObDereferenceObject(m_ClientRequestEventObject);
            m_ClientRequestEventObject = NULL;
        }
        if (m_DefaultFrameBuffer) {
            ExFreePoolWithTag(m_DefaultFrameBuffer, AVSHWS_POOLTAG);
            m_DefaultFrameBuffer = NULL;
        }
        if (m_TemporaryBuffer) {
            ExFreePoolWithTag(m_TemporaryBuffer, AVSHWS_POOLTAG);
            m_TemporaryBuffer = NULL;
        }
        if (m_SynthesisBuffer) {
            ExFreePoolWithTag(m_SynthesisBuffer, AVSHWS_POOLTAG);
            m_SynthesisBuffer = NULL;
        }
    }

    return Status;
        
}

/*************************************************/


NTSTATUS
CHardwareSimulation::
Pause (
    BOOLEAN Pausing
    )

/*++

Routine Description:

    Pause the hardware simulation...  When the hardware simulation is told
    to pause, it stops issuing interrupts, etc...  but it does not reset
    the counters 

Arguments:

    Pausing -
        Indicates whether the hardware is pausing or not. 

        TRUE -
            Pause the hardware

        FALSE -
            Unpause the hardware from a previous pause


Return Value:

    Success / Failure

--*/

{

    PAGED_CODE();

    if (Pausing && m_HardwareState == HardwareRunning) {
        //
        // If we were running, stop completing mappings, etc...
        //
        m_StopHardware = TRUE;
    
        KeWaitForSingleObject (
            &m_HardwareEvent,
            Suspended,
            KernelMode,
            FALSE,
            NULL
            );

        NT_ASSERT (m_StopHardware == FALSE);

        m_HardwareState = HardwarePaused; 

    } else if (!Pausing && m_HardwareState == HardwarePaused) {

        //
        // For unpausing the hardware, we need to compute the relative time
        // and restart interrupts.
        //
        LARGE_INTEGER UnpauseTime;

        KeQuerySystemTimePrecise (&UnpauseTime);
        m_InterruptTime = (ULONG) (
            (UnpauseTime.QuadPart - m_StartTime.QuadPart) /
            m_TimePerFrame
            );

        UnpauseTime.QuadPart = m_StartTime.QuadPart +
            (m_InterruptTime + 1) * m_TimePerFrame;

        m_HardwareState = HardwareRunning;
        KeSetTimer (&m_IsrTimer, UnpauseTime, &m_IsrFakeDpc);

    }

    return STATUS_SUCCESS;

}

#ifdef ALLOC_PRAGMA
#pragma code_seg(push, avshws_stopseg, ".text")
#endif // ALLOC_PRAGMA

NTSTATUS
CHardwareSimulation::
Stop (
    )

/*++

Routine Description:

    Stop the hardware simulation....  Wait until the hardware simulation
    has successfully stopped and then return.

Arguments:

    None

Return Value:

    Success / Failure

--*/

{
    KIRQL Irql;
    DbgPrint("[avshws] HwSim::Stop begin sim=%p state=%lu queued=%lu irql=%lu\n", this, (ULONG)m_HardwareState, m_ScatterGatherMappingsQueued, (ULONG)KeGetCurrentIrql());

    KeCancelTimer (&m_IsrTimer);

    //
    // If the hardware is told to stop while it's running, we need to
    // halt the interrupts first.  If we're already paused, this has
    // already been done.
    //
    if (m_HardwareState == HardwareRunning) {
    
        m_StopHardware = TRUE;
    
        KeWaitForSingleObject (
            &m_HardwareEvent,
            Suspended,
            KernelMode,
            FALSE,
            NULL
            );
    
        NT_ASSERT (m_StopHardware == FALSE);

    }

    m_HardwareState = HardwareStopped;
    m_StopHardware = FALSE;

    //
    // The image synthesizer may still be around.  Just for safety's
    // sake, NULL out the image synthesis buffer and toast it.
    //
    if (m_ImageSynth) {
        m_ImageSynth -> SetBuffer (NULL);
    }

    if (m_SynthesisBuffer) {
        ExFreePoolWithTag (m_SynthesisBuffer, AVSHWS_POOLTAG);
        m_SynthesisBuffer = NULL;
    }

	if (m_TemporaryBuffer) {
		ExFreePoolWithTag(m_TemporaryBuffer, AVSHWS_POOLTAG);
		m_TemporaryBuffer = NULL;
	}

    if (m_DefaultFrameBuffer) {
        ExFreePoolWithTag(m_DefaultFrameBuffer, AVSHWS_POOLTAG);
        m_DefaultFrameBuffer = NULL;
    }

    if (m_ClientRequestEvent) {
        ZwClose(m_ClientRequestEvent);
        m_ClientRequestEvent = NULL;
    }
    if (m_ClientRequestEventObject) {
        ObDereferenceObject(m_ClientRequestEventObject);
        m_ClientRequestEventObject = NULL;
    }

    //
    // Protect the S/G list
    //
    KeAcquireSpinLock (&m_ListLock, &Irql);
    // 
    // Free S/G buffer 
    // 
    // 
    while (m_ScatterGatherMappingsQueued > 0) {
        LIST_ENTRY *listEntry = RemoveHeadList (&m_ScatterGatherMappings);
        m_ScatterGatherMappingsQueued--;
        PSCATTER_GATHER_ENTRY SGEntry =
            reinterpret_cast <PSCATTER_GATHER_ENTRY> (
                CONTAINING_RECORD (
                    listEntry,
                    SCATTER_GATHER_ENTRY,
                    ListEntry
                    )
                );
        // 
        // Release the scatter / gather entry back to our lookaside. 
        // 
        if (m_ScatterGatherLookasideInitialized) {
            ExFreeToLookasideListEx(&m_ScatterGatherLookaside, SGEntry);
        } else {
            ExFreePoolWithTag(SGEntry, kScatterGatherEntryTag);
        }
    } 

    m_NumMappingsCompleted = 0;
    m_ScatterGatherBytesQueued = 0;
    KeReleaseSpinLock (&m_ListLock, Irql);

    DbgPrint("[avshws] HwSim::Stop end sim=%p queued=%lu irql=%lu\n", this, m_ScatterGatherMappingsQueued, (ULONG)KeGetCurrentIrql());

    return STATUS_SUCCESS;

}

#ifdef ALLOC_PRAGMA
#pragma code_seg(pop, avshws_stopseg)
#endif // ALLOC_PRAGMA

/**************************************************************************

    LOCKED CODE

**************************************************************************/

#ifdef ALLOC_PRAGMA
#pragma code_seg()
#endif // ALLOC_PRAGMA

ULONG
CHardwareSimulation::
ReadNumberOfMappingsCompleted (
    )

/*++

Routine Description:

    Read the number of scatter / gather mappings which have been
    completed (TOTAL NUMBER) since the last reset of the simulated
    hardware

Arguments:

    None

Return Value:

    Total number of completed mappings.

--*/

{

    //
    // Don't care if this is being updated this moment in the DPC...  I only
    // need a number to return which isn't too great (too small is ok).
    // In real hardware, this wouldn't be done this way anyway.
    //
    return m_NumMappingsCompleted;

}

/*************************************************/


ULONG
CHardwareSimulation::
ProgramScatterGatherMappings (
    IN PKSSTREAM_POINTER Clone,
    IN PUCHAR *Buffer,
    IN PKSMAPPING Mappings,
    IN ULONG MappingsCount,
    IN ULONG MappingStride
    )

/*++

Routine Description:

    Program the scatter gather mapping list.  This shoves a bunch of 
    entries on a list for access during the fake interrupt.  Note that
    we have physical addresses here only for simulation.  We really
    access via the virtual address....  although we chunk it into multiple
    buffers to more realistically simulate S/G

Arguments:

    Buffer -
        The virtual address of the buffer mapped by the mapping list 

    Mappings -
        The KSMAPPINGS array corresponding to the buffer

    MappingsCount -
        The number of mappings in the mappings array

    MappingStride -
        The mapping stride used in initialization of AVStream DMA

Return Value:

    Number of mappings actually inserted.

--*/

{
    ULONG BytesInserted = 0;
    PSCATTER_GATHER_ENTRY Entry = NULL;

    UNREFERENCED_PARAMETER(Mappings);
    UNREFERENCED_PARAMETER(MappingStride);

    if (!Clone || !Buffer || !*Buffer || MappingsCount == 0) {
        return 0;
    }

    if (m_ScatterGatherLookasideInitialized) {
        Entry = reinterpret_cast <PSCATTER_GATHER_ENTRY> (
            ExAllocateFromLookasideListEx(&m_ScatterGatherLookaside)
            );
    } else {
        Entry = reinterpret_cast <PSCATTER_GATHER_ENTRY> (
            ExAllocatePool2(
                POOL_FLAG_NON_PAGED,
                sizeof(SCATTER_GATHER_ENTRY),
                kScatterGatherEntryTag
                )
            );
    }

    if (!Entry) {
        return 0;
    }

    Entry -> Virtual    = *Buffer;
    Entry -> ByteCount  = MappingsCount;
    Entry -> AdvanceCount = MappingsCount;
    Entry -> CloneEntry = Clone;

    //
    // Move forward before taking the list lock so the lock only protects
    // queue metadata updates.
    //
    *Buffer += MappingsCount;

    KIRQL Irql;
    KeAcquireSpinLock (&m_ListLock, &Irql);
    InsertTailList (&m_ScatterGatherMappings, &(Entry -> ListEntry));
    BytesInserted = MappingsCount;
    m_ScatterGatherMappingsQueued++;
    m_ScatterGatherBytesQueued += MappingsCount;
    KeReleaseSpinLock (&m_ListLock, Irql);

    return BytesInserted;

}

/*************************************************/


NTSTATUS
CHardwareSimulation::
FillScatterGatherBuffers (
    )

/*++

Routine Description:

    The hardware has synthesized a buffer in scratch space and we're to
    fill scatter / gather buffers.

Arguments:

    None

Return Value:

    Success / Failure

--*/

{
    PUCHAR Buffer = reinterpret_cast <PUCHAR> (m_SynthesisBuffer);
    ULONG BufferRemaining = m_ImageSize;

    //
    // For simplification, if there aren't enough scatter / gather buffers
    // queued, we don't partially fill the ones that are available.  We just
    // skip the frame and consider it starvation.
    //
    // This could be enforced by only programming scatter / gather mappings
    // for a buffer if all of them fit in the table also...
    //
    while (BufferRemaining) {
        PSCATTER_GATHER_ENTRY SGEntry = NULL;

        //
        // Protect only list manipulation and shared queue counters.
        //
        KeAcquireSpinLockAtDpcLevel (&m_ListLock);
        if (m_ScatterGatherMappingsQueued == 0 ||
            m_ScatterGatherBytesQueued < BufferRemaining) {
            KeReleaseSpinLockFromDpcLevel (&m_ListLock);
            break;
        }

        LIST_ENTRY *listEntry = RemoveHeadList (&m_ScatterGatherMappings);
        m_ScatterGatherMappingsQueued--;

        SGEntry = reinterpret_cast <PSCATTER_GATHER_ENTRY> (
            CONTAINING_RECORD (
                listEntry,
                SCATTER_GATHER_ENTRY,
                ListEntry
                )
            );
        m_ScatterGatherBytesQueued -= SGEntry -> ByteCount;
        KeReleaseSpinLockFromDpcLevel (&m_ListLock);

        //
        // Since we're software, we'll be accessing this by virtual address...
        //
        if (!SGEntry -> Virtual || !m_ImageSynth) {
            if (m_ScatterGatherLookasideInitialized) {
                ExFreeToLookasideListEx(&m_ScatterGatherLookaside, SGEntry);
            } else {
                ExFreePoolWithTag(SGEntry, kScatterGatherEntryTag);
            }
            return STATUS_INVALID_PARAMETER;
        }

        if (!SGEntry -> CloneEntry || !SGEntry -> CloneEntry -> StreamHeader) {
            if (m_ScatterGatherLookasideInitialized) {
                ExFreeToLookasideListEx(&m_ScatterGatherLookaside, SGEntry);
            } else {
                ExFreePoolWithTag(SGEntry, kScatterGatherEntryTag);
            }
            return STATUS_INVALID_PARAMETER;
        }

        LONG Width = m_Width * (m_ImageSynth -> GetBytesPerPixel());
        LONG Stride = Width;
        BOOLEAN BottomUp = FALSE;
        if (SGEntry -> CloneEntry -> StreamHeader -> Size >=
            sizeof (KSSTREAM_HEADER) + sizeof (KS_FRAME_INFO)) {
            PKS_FRAME_INFO FrameInfo =
                reinterpret_cast <PKS_FRAME_INFO> (
                    SGEntry -> CloneEntry -> StreamHeader + 1
                    );

            if (FrameInfo -> lSurfacePitch != 0) {
                if (FrameInfo -> lSurfacePitch == LONG_MIN) {
                    if (m_ScatterGatherLookasideInitialized) {
                        ExFreeToLookasideListEx(&m_ScatterGatherLookaside, SGEntry);
                    } else {
                        ExFreePoolWithTag(SGEntry, kScatterGatherEntryTag);
                    }
                    return STATUS_INVALID_PARAMETER;
                }

                BottomUp = (FrameInfo -> lSurfacePitch < 0);
                Stride = BottomUp ? -FrameInfo -> lSurfacePitch : FrameInfo -> lSurfacePitch;
            }
        }

        if (Width <= 0 || Stride < Width) {
            if (m_ScatterGatherLookasideInitialized) {
                ExFreeToLookasideListEx(&m_ScatterGatherLookaside, SGEntry);
            } else {
                ExFreePoolWithTag(SGEntry, kScatterGatherEntryTag);
            }
            return STATUS_INVALID_PARAMETER;
        }

        ULONGLONG RowPitch = static_cast <ULONGLONG> (Stride);
        ULONGLONG RequiredBytes = static_cast <ULONGLONG> (Width);
        if (m_Height > 0) {
            RequiredBytes += RowPitch * (m_Height - 1);
        }
        if (RequiredBytes > SGEntry -> ByteCount) {
            if (m_ScatterGatherLookasideInitialized) {
                ExFreeToLookasideListEx(&m_ScatterGatherLookaside, SGEntry);
            } else {
                ExFreePoolWithTag(SGEntry, kScatterGatherEntryTag);
            }
            return STATUS_INSUFFICIENT_RESOURCES;
        }

        PUCHAR DestinationBase = SGEntry -> Virtual;
        if (BottomUp && m_Height > 1) {
            DestinationBase += RowPitch * (m_Height - 1);
        }

        for(ULONG y = 0; y < m_Height; y++)
        {
            PUCHAR Destination =
                BottomUp ?
                    (DestinationBase - (Stride * y)) :
                    (DestinationBase + (Stride * y));

            RtlCopyMemory(Destination, Buffer, Width);
            Buffer += Width;
            BufferRemaining -= Width;
        }

        m_NumMappingsCompleted += SGEntry -> AdvanceCount;

        //
        // Release the scatter / gather entry back to our lookaside.
        //
        if (m_ScatterGatherLookasideInitialized) {
            ExFreeToLookasideListEx(&m_ScatterGatherLookaside, SGEntry);
        } else {
            ExFreePoolWithTag(SGEntry, kScatterGatherEntryTag);
        }

    }

    if (BufferRemaining) return STATUS_INSUFFICIENT_RESOURCES;
    else return STATUS_SUCCESS;
    
}

/*************************************************/


void
CHardwareSimulation::
FakeHardware (
    )

/*++

Routine Description:

    Simulate an interrupt and what the hardware would have done in the
    time since the previous interrupt.

Arguments:

    None

Return Value:

    None

--*/

{

    m_InterruptTime++;

	if (m_HardwareState == HardwareRunning)
	{
        BOOLEAN clientConnected = FALSE;
        LARGE_INTEGER lastFrameTime = {};
        PUCHAR sourceFrame = NULL;

        KeAcquireSpinLockAtDpcLevel(&m_FrameLock);
        clientConnected = m_ClientConnected;
        lastFrameTime = m_LastFrameTime;
        sourceFrame = (clientConnected && m_TemporaryBuffer)
            ? m_TemporaryBuffer
            : (m_DefaultFrameBuffer ? m_DefaultFrameBuffer : m_TemporaryBuffer);
        if (sourceFrame) {
            RtlCopyMemory(m_SynthesisBuffer, sourceFrame, m_ImageSize);
        } else {
            RtlZeroMemory(m_SynthesisBuffer, m_ImageSize);
        }
        KeReleaseSpinLockFromDpcLevel(&m_FrameLock);

        if (clientConnected && lastFrameTime.QuadPart > 0) {
            LARGE_INTEGER now;
            KeQuerySystemTimePrecise(&now);
            if ((now.QuadPart - lastFrameTime.QuadPart) > kClientHeartbeatTimeout100ns) {
                KeAcquireSpinLockAtDpcLevel(&m_FrameLock);
                m_ClientConnected = FALSE;
                clientConnected = FALSE;
                KeReleaseSpinLockFromDpcLevel(&m_FrameLock);
            }
        }

		if (!NT_SUCCESS(FillScatterGatherBuffers())) {
			InterlockedIncrement(PLONG(&m_NumFramesSkipped));
		}
	}

    //
    // Issue an interrupt to our hardware sink.  This is a "fake" interrupt.
    // It will occur at DISPATCH_LEVEL.
    //
    m_HardwareSink -> Interrupt ();

    //
    // Reschedule the timer if the hardware isn't being stopped.
    //
    if (!m_StopHardware) {

        //
        // Reschedule the timer for the next interrupt time.
        //
        LARGE_INTEGER NextTime;
        NextTime.QuadPart = m_StartTime.QuadPart + 
            (m_TimePerFrame * (m_InterruptTime + 1));

        KeSetTimer (&m_IsrTimer, NextTime, &m_IsrFakeDpc);
        
    } else {
        //
        // If someone is waiting on the hardware to stop, raise the stop
        // event and clear the flag.
        //
        m_StopHardware = FALSE;
        KeSetEvent (&m_HardwareEvent, IO_NO_INCREMENT, FALSE);
    }

}


void CHardwareSimulation::SetData(PVOID data, ULONG dataLength)
{
	if (m_HardwareState != HardwareRunning)
	{
		return;
	}

	if (m_TemporaryBuffer == NULL)
	{
		return;
	}

    KIRQL irql;
    BOOLEAN clientConnected = FALSE;
    KeAcquireSpinLock(&m_FrameLock, &irql);
    clientConnected = m_ClientConnected;
    KeReleaseSpinLock(&m_FrameLock, irql);
    if (!clientConnected) {
        return;
    }

	if (dataLength < m_Width * m_Height * 3)
	{
		return;
	}

    LARGE_INTEGER now;
    KeQuerySystemTimePrecise(&now);
    KeAcquireSpinLock(&m_FrameLock, &irql);

    static volatile LONG s_hwFrameSequence = 0;
    LONG seq = _InterlockedIncrement(&s_hwFrameSequence);

	for (ULONG y = 0; y < m_Height; y++)
	{
		PUCHAR buffer = m_TemporaryBuffer + ((m_Width * 3) * (m_Height - 1 - y));
		PUCHAR dataLine = (PUCHAR)(data) + ((m_Width * 3) * y);

		RtlCopyMemory(buffer, dataLine, m_Width * 3);
	}
    m_LastFrameTime = now;
    KeReleaseSpinLock(&m_FrameLock, irql);
    if (seq <= 3 || seq % 30 == 0) {
        DbgPrint("[avshws] HwSim::SetData frame=%ld len=%lu client=%lu irql=%lu\n", seq, dataLength, (ULONG)clientConnected, (ULONG)KeGetCurrentIrql());
    }
}

void CHardwareSimulation::SetClientConnected(BOOLEAN connected)
{
    KIRQL irql;
    KeAcquireSpinLock(&m_FrameLock, &irql);
    m_ClientConnected = connected;
    if (connected) {
        KeQuerySystemTimePrecise(&m_LastFrameTime);
    } else {
        m_LastFrameTime.QuadPart = 0;
    }
    KeReleaseSpinLock(&m_FrameLock, irql);
    DbgPrint("[avshws] HwSim::SetClientConnected connected=%lu irql=%lu\n", (ULONG)connected, (ULONG)KeGetCurrentIrql());
}

BOOLEAN CHardwareSimulation::IsClientConnected()
{
    KIRQL irql;
    BOOLEAN connected = FALSE;
    KeAcquireSpinLock(&m_FrameLock, &irql);
    connected = m_ClientConnected;
    KeReleaseSpinLock(&m_FrameLock, irql);
    return connected;
}

void CHardwareSimulation::NotifyCameraState(BOOLEAN isRunning)
{
    DbgPrint("[avshws] HwSim::NotifyCameraState running=%lu connected=%lu irql=%lu\n", (ULONG)isRunning, (ULONG)IsClientConnected(), (ULONG)KeGetCurrentIrql());
    if (!m_ClientRequestEventObject) {
        return;
    }

    if (isRunning) {
        if (!IsClientConnected()) {
            KeSetEvent(m_ClientRequestEventObject, IO_NO_INCREMENT, FALSE);
        }
    } else {
        KeClearEvent(m_ClientRequestEventObject);
    }
}
