/**************************************************************************

    AVStream Simulated Hardware Sample

    Copyright (c) 2001, Microsoft Corporation.

    File:

        hwsim.cpp

    Abstract:
        
        This file contains the hardware simulation.  It fakes "DMA" transfers,
        scatter gather mapping handling, ISR's, etc...  The ISR routine in
        here will be called when an ISR would be generated by the fake hardware
        and it will directly call into the device level ISR for more accurate
        simulation.

    History:

        created 3/9/2001

**************************************************************************/

#include "avshws.h"

/*************************************************/
KDEFERRED_ROUTINE SimulatedInterrupt;
static const LONGLONG kClientHeartbeatTimeout100ns = 20000000LL;
static const ULONG kScatterGatherEntryTag = 'nEGS';
static const ULONG kSetDataRejectNone = 0;
static const ULONG kSetDataRejectNotRunning = 1;
static const ULONG kSetDataRejectNoBuffer = 2;
static const ULONG kSetDataRejectNotConnected = 3;
static const ULONG kSetDataRejectNoSynth = 4;
static const ULONG kSetDataRejectBadGeometry = 5;
static const ULONG kSetDataRejectShortSource = 6;
static const ULONG kUserFrameStartupGraceInterrupts = 90;

namespace
{
    const UCHAR kPlaceholderBlue = 217;
    const UCHAR kPlaceholderGreen = 26;
    const UCHAR kPlaceholderRed = 13;

    const UCHAR kPlaceholderTextBlue = 64;
    const UCHAR kPlaceholderTextGreen = 255;
    const UCHAR kPlaceholderTextRed = 38;

    const UCHAR kFontP[16][16] = {
        {0,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0},
        {0,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,1,1,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,1,1,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0},
        {0,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0},
        {0,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}
    };

    const UCHAR kFontC[16][16] = {
        {0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0},
        {0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0},
        {0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,0},
        {0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0},
        {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
        {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}
    };

    void FillPlaceholderFrameRgb24(
        _Out_writes_bytes_(imageSize) PUCHAR buffer,
        ULONG width,
        ULONG height,
        ULONG imageSize)
    {
        if (!buffer || width == 0 || height == 0) {
            return;
        }

        RtlZeroMemory(buffer, imageSize);

        const ULONG stride = width * 3;
        for (ULONG y = 0; y < height; ++y) {
            UCHAR* row = buffer + (stride * y);
            const ULONG scanlineTint = (y & 1) ? 10 : 0;

            for (ULONG x = 0; x < width; ++x) {
                const ULONG pixel = x * 3;
                row[pixel + 0] = static_cast<UCHAR>(kPlaceholderBlue - scanlineTint);
                row[pixel + 1] = static_cast<UCHAR>(kPlaceholderGreen + (scanlineTint / 3));
                row[pixel + 2] = static_cast<UCHAR>(kPlaceholderRed + (scanlineTint / 4));
            }
        }

        ULONG glyphScale = height / 40;
        if ((width / 80) < glyphScale) {
            glyphScale = width / 80;
        }
        if (glyphScale < 2) {
            glyphScale = 2;
        }
        const ULONG glyphWidth = 16 * glyphScale;
        const ULONG glyphHeight = 16 * glyphScale;
        const ULONG glyphGap = 6 * glyphScale;
        ULONG marginX = width / 16;
        ULONG marginY = height / 14;
        if (marginX < 12) {
            marginX = 12;
        }
        if (marginY < 12) {
            marginY = 12;
        }
        const ULONG totalWidth = (2 * glyphWidth) + glyphGap;

        if (glyphWidth == 0 || glyphHeight == 0 || totalWidth >= width || glyphHeight >= height) {
            return;
        }

        const ULONG originX = width - marginX - totalWidth;
        const ULONG originY = marginY;

        for (ULONG py = 0; py < glyphHeight; ++py) {
            ULONG fontY = py / glyphScale;
            if (fontY > 15) {
                fontY = 15;
            }
            const ULONG rowY = originY + py;
            if (rowY >= height) {
                break;
            }

            for (ULONG px = 0; px < totalWidth; ++px) {
                ULONG fontX = 0;
                BOOLEAN drawPixel = FALSE;

                if (px < glyphWidth) {
                    fontX = px / glyphScale;
                    if (fontX > 15) {
                        fontX = 15;
                    }
                    drawPixel = (kFontP[fontY][fontX] != 0);
                } else if (px >= (glyphWidth + glyphGap)) {
                    fontX = (px - glyphWidth - glyphGap) / glyphScale;
                    if (fontX > 15) {
                        fontX = 15;
                    }
                    drawPixel = (kFontC[fontY][fontX] != 0);
                }

                if (!drawPixel) {
                    continue;
                }

                const ULONG rowX = originX + px;
                if (rowX >= width) {
                    continue;
                }

                UCHAR* pixel = buffer + (rowY * stride) + (rowX * 3);
                pixel[0] = kPlaceholderTextBlue;
                pixel[1] = kPlaceholderTextGreen;
                pixel[2] = kPlaceholderTextRed;
            }
        }
    }

    inline UCHAR ClampToByte(LONG value)
    {
        if (value < 0) {
            return 0;
        }
        if (value > 255) {
            return 255;
        }
        return static_cast<UCHAR>(value);
    }

    inline void Rgb24ToYuv(
        UCHAR red,
        UCHAR green,
        UCHAR blue,
        _Out_ UCHAR* y,
        _Out_ UCHAR* u,
        _Out_ UCHAR* v)
    {
        *y = ClampToByte((((66 * red) + (129 * green) + (25 * blue) + 128) >> 8) + 16);
        *u = ClampToByte((((-38 * red) - (74 * green) + (112 * blue) + 128) >> 8) + 128);
        *v = ClampToByte((((112 * red) - (94 * green) - (18 * blue) + 128) >> 8) + 128);
    }

    void ConvertRgb24ToYuy2Frame(
        _Out_writes_bytes_(destinationLength) PUCHAR destination,
        ULONG destinationLength,
        _In_reads_bytes_(sourceLength) const UCHAR* source,
        ULONG sourceLength,
        ULONG width,
        ULONG height)
    {
        UNREFERENCED_PARAMETER(destinationLength);
        UNREFERENCED_PARAMETER(sourceLength);

        const ULONG srcStride = width * 3;
        const ULONG dstStride = width * 2;

        for (ULONG y = 0; y < height; ++y) {
            const UCHAR* srcRow = source + (srcStride * y);
            UCHAR* dstRow = destination + (dstStride * y);

            for (ULONG x = 0; x < width; x += 2) {
                const UCHAR* pixel0 = srcRow + (x * 3);
                const UCHAR* pixel1 = (x + 1 < width) ? (pixel0 + 3) : pixel0;

                UCHAR y0 = 0;
                UCHAR u0 = 0;
                UCHAR v0 = 0;
                UCHAR y1 = 0;
                UCHAR u1 = 0;
                UCHAR v1 = 0;

                Rgb24ToYuv(pixel0[2], pixel0[1], pixel0[0], &y0, &u0, &v0);
                Rgb24ToYuv(pixel1[2], pixel1[1], pixel1[0], &y1, &u1, &v1);

                const ULONG dst = x * 2;
                dstRow[dst + 0] = y0;
                dstRow[dst + 1] = static_cast<UCHAR>(((ULONG)u0 + (ULONG)u1) / 2);
                dstRow[dst + 2] = y1;
                dstRow[dst + 3] = static_cast<UCHAR>(((ULONG)v0 + (ULONG)v1) / 2);
            }
        }
    }
}

void
SimulatedInterrupt (
    IN PKDPC Dpc,
    IN PVOID DeferredContext,
    IN PVOID SystemArg1,
    IN PVOID SystemArg2
    )
{
    CHardwareSimulation* HardwareSim = (CHardwareSimulation*)DeferredContext;
    
    if (HardwareSim)
    {
        HardwareSim -> FakeHardware ();
    }
}


/**************************************************************************

    PAGEABLE CODE

**************************************************************************/

#ifdef ALLOC_PRAGMA
#pragma code_seg("PAGE")
#endif // ALLOC_PRAGMA



CHardwareSimulation::
CHardwareSimulation (
    IN IHardwareSink *HardwareSink
    ) :
    m_HardwareSink (HardwareSink),
    m_ScatterGatherMappingsMax (SCATTER_GATHER_MAPPINGS_MAX),
    m_ScatterGatherLookasideInitialized (FALSE)

/*++

Routine Description:

    Construct a hardware simulation

Arguments:

    HardwareSink -
        The hardware sink interface.  This is used to trigger
        fake interrupt service routines from.

Return Value:

    Success / Failure

--*/

{

    PAGED_CODE();

    //
    // Initialize the DPC's, timer's, and locks necessary to simulate
    // this capture hardware.
    //
    KeInitializeDpc (
        &m_IsrFakeDpc, 
        SimulatedInterrupt, 
        this
        );

    KeInitializeEvent (
        &m_HardwareEvent,
        SynchronizationEvent,
        FALSE
        );

    KeInitializeTimer (&m_IsrTimer);

    KeInitializeSpinLock (&m_ListLock);
    KeInitializeSpinLock (&m_FrameLock);
    NTSTATUS LookasideStatus = ExInitializeLookasideListEx(
        &m_ScatterGatherLookaside,
        NULL,
        NULL,
        NonPagedPoolNx,
        0,
        sizeof(SCATTER_GATHER_ENTRY),
        kScatterGatherEntryTag,
        0);
    if (NT_SUCCESS(LookasideStatus)) {
        m_ScatterGatherLookasideInitialized = TRUE;
    }

    UNICODE_STRING eventName;
    RtlInitUnicodeString(&eventName, L"\\BaseNamedObjects\\VirtuaCamClientRequest");
    m_ClientRequestEventObject = IoCreateNotificationEvent(&eventName, &m_ClientRequestEvent);
    if (m_ClientRequestEventObject) {
        ObReferenceObject(m_ClientRequestEventObject);
        ZwClose(m_ClientRequestEvent);
        m_ClientRequestEvent = NULL;
        KeClearEvent(m_ClientRequestEventObject);
    } else {
        DbgPrint("[avshws] IoCreateNotificationEvent failed in ctor sim=%p\n", this);
    }

}

CHardwareSimulation::
~CHardwareSimulation (
    )
{
    if (m_HardwareState != HardwareStopped ||
        m_SynthesisBuffer ||
        m_TemporaryBuffer ||
        m_DefaultFrameBuffer ||
        m_ClientRequestEvent ||
        m_ScatterGatherMappingsQueued) {
        (void)Stop ();
    }

    ReleaseClientEventObject();

    if (m_ScatterGatherLookasideInitialized) {
        ExDeleteLookasideListEx(&m_ScatterGatherLookaside);
    }
}

/*************************************************/


CHardwareSimulation *
CHardwareSimulation::
Initialize (
    IN KSOBJECT_BAG Bag,
    IN IHardwareSink *HardwareSink
    )

/*++

Routine Description:

    Initialize the hardware simulation

Arguments:

    HardwareSink -
        The hardware sink interface.  This is what ISR's will be
        triggered through.

Return Value:

    A fully initialized hardware simulation or NULL if the simulation
    could not be initialized.

--*/

{

    PAGED_CODE();

    CHardwareSimulation *HwSim = 
        new (NonPagedPoolNx, 'miSH') CHardwareSimulation (HardwareSink);

    return HwSim;

}

/*************************************************/

#ifdef ALLOC_PRAGMA
#pragma code_seg()
#endif // ALLOC_PRAGMA

void
CHardwareSimulation::
ReleaseFrameBuffers (
    )
{
    if (m_ImageSynth) {
        m_ImageSynth->SetBuffer(NULL);
    }

    if (m_SynthesisBuffer) {
        ExFreePoolWithTag(m_SynthesisBuffer, AVSHWS_POOLTAG);
        m_SynthesisBuffer = NULL;
    }

    if (m_TemporaryBuffer) {
        ExFreePoolWithTag(m_TemporaryBuffer, AVSHWS_POOLTAG);
        m_TemporaryBuffer = NULL;
    }

    if (m_DefaultFrameBuffer) {
        ExFreePoolWithTag(m_DefaultFrameBuffer, AVSHWS_POOLTAG);
        m_DefaultFrameBuffer = NULL;
    }
}

void
CHardwareSimulation::
ReleaseClientEventObject (
    )
{
    if (m_ClientRequestEvent) {
        ZwClose(m_ClientRequestEvent);
        m_ClientRequestEvent = NULL;
    }

    if (m_ClientRequestEventObject) {
        ObDereferenceObject(m_ClientRequestEventObject);
        m_ClientRequestEventObject = NULL;
    }
}

/*************************************************/


NTSTATUS
CHardwareSimulation::
Start (
    IN CImageSynthesizer *ImageSynth,
    IN LONGLONG TimePerFrame,
    IN ULONG Width,
    IN ULONG Height,
    IN ULONG ImageSize
    )

/*++

Routine Description:

    Start the hardware simulation.  This will kick the interrupts on,
    begin issuing DPC's, filling in capture information, etc...
    We keep track of starvation starting at this point.

Arguments:

    ImageSynth -
        The image synthesizer to use to generate pictures to display
        on the capture buffer.

    TimePerFrame -
        The time per frame...  we issue interrupts this often.

    Width -
        The image width

    Height -
        The image height

    ImageSize - 
        The size of the image.  We allocate a temporary scratch buffer
        based on this size to fake hardware.

Return Value:

    Success / Failure (typical failure will be out of memory on the 
    scratch buffer, etc...)

--*/

{
    NTSTATUS Status = STATUS_SUCCESS;

    m_ImageSynth = ImageSynth;
    m_TimePerFrame = TimePerFrame;
    m_ImageSize = ImageSize;
    m_Height = Height;
    m_Width = Width;

    InitializeListHead (&m_ScatterGatherMappings);
    m_NumMappingsCompleted = 0;
    m_ScatterGatherMappingsQueued = 0;
    m_NumFramesSkipped = 0;
    m_InterruptTime = 0;
    m_LastFillStatus = static_cast<ULONG>(STATUS_SUCCESS);
    m_LastFillStride = 0;
    m_LastFillWidthBytes = 0;
    m_LastFillRequiredBytes = 0;
    m_LastFillByteCount = 0;
    m_LastFillBufferRemaining = 0;
    m_LastCompletedDelta = 0;
    m_LastSetDataLength = 0;
    m_SetDataAcceptedCount = 0;
    m_SetDataRejectedCount = 0;
    m_LastSetDataReason = kSetDataRejectNone;

    KeQuerySystemTimePrecise (&m_StartTime);

    //
    // Allocate a scratch buffer for the synthesizer.
    //
    m_SynthesisBuffer = reinterpret_cast <PUCHAR> (
        ExAllocatePool2 (
            POOL_FLAG_NON_PAGED,
            m_ImageSize,
            AVSHWS_POOLTAG
            )
        );

    if (!m_SynthesisBuffer) {
        Status = STATUS_INSUFFICIENT_RESOURCES;
    }

	//
	// Allocate a temporary frame buffer;
	//
	m_TemporaryBuffer = reinterpret_cast <PUCHAR> (
		ExAllocatePool2(
			POOL_FLAG_NON_PAGED,
			m_ImageSize,
			AVSHWS_POOLTAG
			)
		);

	if (!m_TemporaryBuffer) {
		Status = STATUS_INSUFFICIENT_RESOURCES;
	}

    m_DefaultFrameBuffer = reinterpret_cast<PUCHAR>(
        ExAllocatePool2(
            POOL_FLAG_NON_PAGED,
            m_ImageSize,
            AVSHWS_POOLTAG));
    if (!m_DefaultFrameBuffer) {
        Status = STATUS_INSUFFICIENT_RESOURCES;
    } else {
        if (m_ImageSynth && m_ImageSynth->GetBytesPerPixel() == 3) {
            FillPlaceholderFrameRgb24(m_DefaultFrameBuffer, m_Width, m_Height, m_ImageSize);
        }
    }

    if (NT_SUCCESS(Status) && !m_ClientRequestEventObject) {
        DbgPrint("[avshws] HwSim::Start no client-request event; continuing without side-channel sim=%p\n", this);
    }

    //
    // If everything is ok, start issuing interrupts.
    //
    if (NT_SUCCESS (Status)) {
        KIRQL irql;
        KeAcquireSpinLock(&m_FrameLock, &irql);
        m_HardwareState = HardwareRunning;
        if (m_ClientConnected) {
            KeQuerySystemTimePrecise(&m_LastFrameTime);
        } else {
            m_LastFrameTime.QuadPart = 0;
        }
        KeReleaseSpinLock(&m_FrameLock, irql);

        //
        // Set up the synthesizer with the width, height, and scratch buffer.
        //
        m_ImageSynth -> SetImageSize (m_Width, m_Height);
        m_ImageSynth -> SetBuffer (m_SynthesisBuffer);

        LARGE_INTEGER NextTime;
        NextTime.QuadPart = m_StartTime.QuadPart + m_TimePerFrame;

        KeSetTimer (&m_IsrTimer, NextTime, &m_IsrFakeDpc);

    }
    else {
        ReleaseFrameBuffers();
    }

    return Status;
        
}

#ifdef ALLOC_PRAGMA
#pragma code_seg()
#endif // ALLOC_PRAGMA

/*************************************************/


NTSTATUS
CHardwareSimulation::
Pause (
    BOOLEAN Pausing
    )

/*++

Routine Description:

    Pause the hardware simulation...  When the hardware simulation is told
    to pause, it stops issuing interrupts, etc...  but it does not reset
    the counters 

Arguments:

    Pausing -
        Indicates whether the hardware is pausing or not. 

        TRUE -
            Pause the hardware

        FALSE -
            Unpause the hardware from a previous pause


Return Value:

    Success / Failure

--*/

{
    if (Pausing) {
        //
        // If we were running, stop completing mappings, etc...
        //
        KIRQL irql;
        KeCancelTimer(&m_IsrTimer);
        (void)KeRemoveQueueDpc(&m_IsrFakeDpc);

        KeAcquireSpinLock(&m_FrameLock, &irql);
        if (m_HardwareState == HardwareRunning) {
            m_HardwareState = HardwarePaused;
        }
        KeReleaseSpinLock(&m_FrameLock, irql);

        while (InterlockedCompareExchange(&m_DpcActive, 0, 0) != 0) {
            KeStallExecutionProcessor(50);
        }

    } else {
        BOOLEAN shouldRestart = FALSE;

        //
        // For unpausing the hardware, we need to compute the relative time
        // and restart interrupts.
        //
        KIRQL irql;
        KeAcquireSpinLock(&m_FrameLock, &irql);
        if (m_HardwareState == HardwarePaused) {
            LARGE_INTEGER now;
            KeQuerySystemTimePrecise(&now);
            m_InterruptTime = (ULONG)(
                (now.QuadPart - m_StartTime.QuadPart) /
                m_TimePerFrame
                );
            m_HardwareState = HardwareRunning;
            if (m_ClientConnected) {
                m_LastFrameTime = now;
            }
            shouldRestart = TRUE;
        }
        KeReleaseSpinLock(&m_FrameLock, irql);

        if (shouldRestart) {
            LARGE_INTEGER UnpauseTime;
            UnpauseTime.QuadPart = m_StartTime.QuadPart +
                (m_InterruptTime + 1) * m_TimePerFrame;
            KeSetTimer(&m_IsrTimer, UnpauseTime, &m_IsrFakeDpc);
        }

    }

    return STATUS_SUCCESS;

}

#ifdef ALLOC_PRAGMA
#pragma code_seg(push, avshws_stopseg, ".text")
#endif // ALLOC_PRAGMA

NTSTATUS
CHardwareSimulation::
Stop (
    )

/*++

Routine Description:

    Stop the hardware simulation....  Wait until the hardware simulation
    has successfully stopped and then return.

Arguments:

    None

Return Value:

    Success / Failure

--*/

{
    KIRQL Irql;
    PUCHAR synthesisBuffer = NULL;
    PUCHAR temporaryBuffer = NULL;
    PUCHAR defaultFrameBuffer = NULL;
    DbgPrint("[avshws] HwSim::Stop begin sim=%p state=%lu queued=%lu irql=%lu\n", this, (ULONG)m_HardwareState, m_ScatterGatherMappingsQueued, (ULONG)KeGetCurrentIrql());

    KeCancelTimer (&m_IsrTimer);
    (void)KeRemoveQueueDpc(&m_IsrFakeDpc);

    KeAcquireSpinLock(&m_FrameLock, &Irql);
    m_HardwareState = HardwareStopped;
    m_StopHardware = FALSE;
    m_LastFrameTime.QuadPart = 0;
    synthesisBuffer = m_SynthesisBuffer;
    temporaryBuffer = m_TemporaryBuffer;
    defaultFrameBuffer = m_DefaultFrameBuffer;
    m_SynthesisBuffer = NULL;
    m_TemporaryBuffer = NULL;
    m_DefaultFrameBuffer = NULL;
    KeReleaseSpinLock(&m_FrameLock, Irql);

    while (InterlockedCompareExchange(&m_DpcActive, 0, 0) != 0 ||
        InterlockedCompareExchange(&m_FrameWriteActive, 0, 0) != 0) {
        KeStallExecutionProcessor(50);
    }

    if (m_ImageSynth) {
        m_ImageSynth->SetBuffer(NULL);
    }

    if (synthesisBuffer) {
        ExFreePoolWithTag(synthesisBuffer, AVSHWS_POOLTAG);
    }

    if (temporaryBuffer) {
        ExFreePoolWithTag(temporaryBuffer, AVSHWS_POOLTAG);
    }

    if (defaultFrameBuffer) {
        ExFreePoolWithTag(defaultFrameBuffer, AVSHWS_POOLTAG);
    }

    //
    // Protect the S/G list
    //
    KeAcquireSpinLock (&m_ListLock, &Irql);
    // 
    // Free S/G buffer 
    // 
    // 
    while (m_ScatterGatherMappingsQueued > 0) {
        LIST_ENTRY *listEntry = RemoveHeadList (&m_ScatterGatherMappings);
        m_ScatterGatherMappingsQueued--;
        PSCATTER_GATHER_ENTRY SGEntry =
            reinterpret_cast <PSCATTER_GATHER_ENTRY> (
                CONTAINING_RECORD (
                    listEntry,
                    SCATTER_GATHER_ENTRY,
                    ListEntry
                    )
                );
        // 
        // Release the scatter / gather entry back to our lookaside. 
        // 
        if (m_ScatterGatherLookasideInitialized) {
            ExFreeToLookasideListEx(&m_ScatterGatherLookaside, SGEntry);
        } else {
            ExFreePoolWithTag(SGEntry, kScatterGatherEntryTag);
        }
    } 

    m_NumMappingsCompleted = 0;
    m_ScatterGatherBytesQueued = 0;
    KeReleaseSpinLock (&m_ListLock, Irql);

    DbgPrint("[avshws] HwSim::Stop end sim=%p queued=%lu irql=%lu\n", this, m_ScatterGatherMappingsQueued, (ULONG)KeGetCurrentIrql());

    return STATUS_SUCCESS;

}

#ifdef ALLOC_PRAGMA
#pragma code_seg(pop, avshws_stopseg)
#endif // ALLOC_PRAGMA

/**************************************************************************

    LOCKED CODE

**************************************************************************/

#ifdef ALLOC_PRAGMA
#pragma code_seg()
#endif // ALLOC_PRAGMA

ULONG
CHardwareSimulation::
ReadNumberOfMappingsCompleted (
    )

/*++

Routine Description:

    Read the number of scatter / gather mappings which have been
    completed (TOTAL NUMBER) since the last reset of the simulated
    hardware

Arguments:

    None

Return Value:

    Total number of completed mappings.

--*/

{

    //
    // Don't care if this is being updated this moment in the DPC...  I only
    // need a number to return which isn't too great (too small is ok).
    // In real hardware, this wouldn't be done this way anyway.
    //
    return m_NumMappingsCompleted;

}

/*************************************************/


ULONG
CHardwareSimulation::
ProgramScatterGatherMappings (
    IN PKSSTREAM_POINTER Clone,
    IN PUCHAR *Buffer,
    IN PKSMAPPING Mappings,
    IN ULONG MappingsCount,
    IN ULONG MappingStride
    )

/*++

Routine Description:

    Program the scatter gather mapping list.  This shoves a bunch of 
    entries on a list for access during the fake interrupt.  Note that
    we have physical addresses here only for simulation.  We really
    access via the virtual address....  although we chunk it into multiple
    buffers to more realistically simulate S/G

Arguments:

    Buffer -
        The virtual address of the buffer mapped by the mapping list 

    Mappings -
        The KSMAPPINGS array corresponding to the buffer

    MappingsCount -
        The number of mappings in the mappings array

    MappingStride -
        The mapping stride used in initialization of AVStream DMA

Return Value:

    Number of mappings actually inserted.

--*/

{
    ULONG BytesInserted = 0;
    PSCATTER_GATHER_ENTRY Entry = NULL;

    UNREFERENCED_PARAMETER(Mappings);
    UNREFERENCED_PARAMETER(MappingStride);

    if (!Clone || !Buffer || !*Buffer || MappingsCount == 0) {
        return 0;
    }

    if (m_ScatterGatherLookasideInitialized) {
        Entry = reinterpret_cast <PSCATTER_GATHER_ENTRY> (
            ExAllocateFromLookasideListEx(&m_ScatterGatherLookaside)
            );
    } else {
        Entry = reinterpret_cast <PSCATTER_GATHER_ENTRY> (
            ExAllocatePool2(
                POOL_FLAG_NON_PAGED,
                sizeof(SCATTER_GATHER_ENTRY),
                kScatterGatherEntryTag
                )
            );
    }

    if (!Entry) {
        return 0;
    }

    Entry -> Virtual    = *Buffer;
    Entry -> ByteCount  = MappingsCount;
    Entry -> AdvanceCount = MappingsCount;
    Entry -> CloneEntry = Clone;

    //
    // Move forward before taking the list lock so the lock only protects
    // queue metadata updates.
    //
    *Buffer += MappingsCount;

    KIRQL Irql;
    KeAcquireSpinLock (&m_ListLock, &Irql);
    InsertTailList (&m_ScatterGatherMappings, &(Entry -> ListEntry));
    BytesInserted = MappingsCount;
    m_ScatterGatherMappingsQueued++;
    m_ScatterGatherBytesQueued += MappingsCount;
    KeReleaseSpinLock (&m_ListLock, Irql);

    return BytesInserted;

}

/*************************************************/


NTSTATUS
CHardwareSimulation::
FillScatterGatherBuffers (
    )

/*++

Routine Description:

    The hardware has synthesized a buffer in scratch space and we're to
    fill scatter / gather buffers.

Arguments:

    None

Return Value:

    Success / Failure

--*/

{
    PUCHAR Buffer = reinterpret_cast <PUCHAR> (m_SynthesisBuffer);
    ULONG BufferRemaining = m_ImageSize;

    //
    // For simplification, if there aren't enough scatter / gather buffers
    // queued, we don't partially fill the ones that are available.  We just
    // skip the frame and consider it starvation.
    //
    // This could be enforced by only programming scatter / gather mappings
    // for a buffer if all of them fit in the table also...
    //
    while (BufferRemaining) {
        PSCATTER_GATHER_ENTRY SGEntry = NULL;

        //
        // Protect only list manipulation and shared queue counters.
        //
        KeAcquireSpinLockAtDpcLevel (&m_ListLock);
        if (m_ScatterGatherMappingsQueued == 0 ||
            m_ScatterGatherBytesQueued < BufferRemaining) {
            KeReleaseSpinLockFromDpcLevel (&m_ListLock);
            break;
        }

        LIST_ENTRY *listEntry = RemoveHeadList (&m_ScatterGatherMappings);
        m_ScatterGatherMappingsQueued--;

        SGEntry = reinterpret_cast <PSCATTER_GATHER_ENTRY> (
            CONTAINING_RECORD (
                listEntry,
                SCATTER_GATHER_ENTRY,
                ListEntry
                )
            );
        m_ScatterGatherBytesQueued -= SGEntry -> ByteCount;
        KeReleaseSpinLockFromDpcLevel (&m_ListLock);

        //
        // Since we're software, we'll be accessing this by virtual address...
        //
        if (!SGEntry -> Virtual || !m_ImageSynth) {
            if (m_ScatterGatherLookasideInitialized) {
                ExFreeToLookasideListEx(&m_ScatterGatherLookaside, SGEntry);
            } else {
                ExFreePoolWithTag(SGEntry, kScatterGatherEntryTag);
            }
            return STATUS_INVALID_PARAMETER;
        }

        if (!SGEntry -> CloneEntry || !SGEntry -> CloneEntry -> StreamHeader) {
            if (m_ScatterGatherLookasideInitialized) {
                ExFreeToLookasideListEx(&m_ScatterGatherLookaside, SGEntry);
            } else {
                ExFreePoolWithTag(SGEntry, kScatterGatherEntryTag);
            }
            return STATUS_INVALID_PARAMETER;
        }

        LONG Width = m_Width * (m_ImageSynth -> GetBytesPerPixel());
        LONG Stride = Width;
        BOOLEAN BottomUp = FALSE;
        if (SGEntry -> CloneEntry -> StreamHeader -> Size >=
            sizeof (KSSTREAM_HEADER) + sizeof (KS_FRAME_INFO)) {
            PKS_FRAME_INFO FrameInfo =
                reinterpret_cast <PKS_FRAME_INFO> (
                    SGEntry -> CloneEntry -> StreamHeader + 1
                    );

            if (FrameInfo -> lSurfacePitch != 0) {
                if (FrameInfo -> lSurfacePitch == LONG_MIN) {
                    if (m_ScatterGatherLookasideInitialized) {
                        ExFreeToLookasideListEx(&m_ScatterGatherLookaside, SGEntry);
                    } else {
                        ExFreePoolWithTag(SGEntry, kScatterGatherEntryTag);
                    }
                    return STATUS_INVALID_PARAMETER;
                }

                BottomUp = (FrameInfo -> lSurfacePitch < 0);
                Stride = BottomUp ? -FrameInfo -> lSurfacePitch : FrameInfo -> lSurfacePitch;
            }
        }

        m_LastFillStride = static_cast<ULONG>(Stride);
        m_LastFillWidthBytes = (Width > 0) ? static_cast<ULONG>(Width) : 0;
        m_LastFillByteCount = SGEntry -> ByteCount;

        if (Width <= 0 || Stride < Width) {
            m_LastFillStatus = static_cast<ULONG>(STATUS_INVALID_PARAMETER);
            m_LastFillRequiredBytes = 0;
            m_LastFillBufferRemaining = BufferRemaining;
            if (m_ScatterGatherLookasideInitialized) {
                ExFreeToLookasideListEx(&m_ScatterGatherLookaside, SGEntry);
            } else {
                ExFreePoolWithTag(SGEntry, kScatterGatherEntryTag);
            }
            return STATUS_INVALID_PARAMETER;
        }

        ULONGLONG RowPitch = static_cast <ULONGLONG> (Stride);
        ULONGLONG RequiredBytes = static_cast <ULONGLONG> (Width);
        if (m_Height > 0) {
            RequiredBytes += RowPitch * (m_Height - 1);
        }
        m_LastFillRequiredBytes = static_cast<ULONG>(RequiredBytes <= MAXULONG ? RequiredBytes : MAXULONG);
        if (RequiredBytes > SGEntry -> ByteCount) {
            m_LastFillStatus = static_cast<ULONG>(STATUS_INSUFFICIENT_RESOURCES);
            m_LastFillBufferRemaining = BufferRemaining;
            if (m_ScatterGatherLookasideInitialized) {
                ExFreeToLookasideListEx(&m_ScatterGatherLookaside, SGEntry);
            } else {
                ExFreePoolWithTag(SGEntry, kScatterGatherEntryTag);
            }
            return STATUS_INSUFFICIENT_RESOURCES;
        }

        PUCHAR DestinationBase = SGEntry -> Virtual;
        if (BottomUp && m_Height > 1) {
            DestinationBase += RowPitch * (m_Height - 1);
        }

        for(ULONG y = 0; y < m_Height; y++)
        {
            PUCHAR Destination =
                BottomUp ?
                    (DestinationBase - (Stride * y)) :
                    (DestinationBase + (Stride * y));

            RtlCopyMemory(Destination, Buffer, Width);
            Buffer += Width;
            BufferRemaining -= Width;
        }

        m_NumMappingsCompleted += SGEntry -> AdvanceCount;
        m_LastCompletedDelta = SGEntry -> AdvanceCount;

        //
        // Release the scatter / gather entry back to our lookaside.
        //
        if (m_ScatterGatherLookasideInitialized) {
            ExFreeToLookasideListEx(&m_ScatterGatherLookaside, SGEntry);
        } else {
            ExFreePoolWithTag(SGEntry, kScatterGatherEntryTag);
        }

    }

    if (BufferRemaining) {
        m_LastFillStatus = static_cast<ULONG>(STATUS_INSUFFICIENT_RESOURCES);
        m_LastFillBufferRemaining = BufferRemaining;
        return STATUS_INSUFFICIENT_RESOURCES;
    }

    m_LastFillStatus = static_cast<ULONG>(STATUS_SUCCESS);
    m_LastFillBufferRemaining = 0;
    return STATUS_SUCCESS;
    
}

/*************************************************/


void
CHardwareSimulation::
FakeHardware (
    )

/*++

Routine Description:

    Simulate an interrupt and what the hardware would have done in the
    time since the previous interrupt.

Arguments:

    None

Return Value:

    None

--*/

{

    m_InterruptTime++;
    InterlockedIncrement(&m_DpcActive);

    HARDWARE_STATE hardwareState = HardwareStopped;
    BOOLEAN clientConnected = FALSE;
    ULONG acceptedFrameCount = 0;
    LARGE_INTEGER lastFrameTime = {};
    PUCHAR sourceFrame = NULL;
    PUCHAR synthesisBuffer = NULL;
    ULONG imageSize = 0;

    KeAcquireSpinLockAtDpcLevel(&m_FrameLock);
    hardwareState = m_HardwareState;
    clientConnected = m_ClientConnected;
    acceptedFrameCount = m_SetDataAcceptedCount;
    lastFrameTime = m_LastFrameTime;
    synthesisBuffer = m_SynthesisBuffer;
    imageSize = m_ImageSize;
    if (hardwareState == HardwareRunning) {
        const BOOLEAN useUploadedFrame =
            (acceptedFrameCount > 0) &&
            (m_InterruptTime >= kUserFrameStartupGraceInterrupts);
        sourceFrame = (useUploadedFrame && m_TemporaryBuffer)
            ? m_TemporaryBuffer
            : (m_DefaultFrameBuffer ? m_DefaultFrameBuffer : m_TemporaryBuffer);
    }
    KeReleaseSpinLockFromDpcLevel(&m_FrameLock);

    if (hardwareState == HardwareRunning) {
        if (sourceFrame && synthesisBuffer && imageSize > 0) {
            RtlCopyMemory(synthesisBuffer, sourceFrame, imageSize);
        } else if (synthesisBuffer && imageSize > 0) {
            RtlZeroMemory(synthesisBuffer, imageSize);
        }
    }

    if (hardwareState == HardwareRunning &&
        clientConnected &&
        lastFrameTime.QuadPart > 0 &&
        m_SetDataAcceptedCount > 0) {
        LARGE_INTEGER now;
        KeQuerySystemTimePrecise(&now);
        if ((now.QuadPart - lastFrameTime.QuadPart) > kClientHeartbeatTimeout100ns) {
            KeAcquireSpinLockAtDpcLevel(&m_FrameLock);
            m_ClientConnected = FALSE;
            clientConnected = FALSE;
            KeReleaseSpinLockFromDpcLevel(&m_FrameLock);
        }
    }

	if (hardwareState == HardwareRunning &&
        !NT_SUCCESS(FillScatterGatherBuffers())) {
		InterlockedIncrement(PLONG(&m_NumFramesSkipped));
	}

    //
    // Issue an interrupt to our hardware sink.  This is a "fake" interrupt.
    // It will occur at DISPATCH_LEVEL.
    //
    if (hardwareState == HardwareRunning && m_HardwareSink) {
        m_HardwareSink -> Interrupt ();
    }

    //
    // Reschedule the timer if the hardware isn't being stopped.
    //
    KeAcquireSpinLockAtDpcLevel(&m_FrameLock);
    hardwareState = m_HardwareState;
    KeReleaseSpinLockFromDpcLevel(&m_FrameLock);

    if (hardwareState == HardwareRunning) {
        LARGE_INTEGER NextTime;
        NextTime.QuadPart = m_StartTime.QuadPart +
            (m_TimePerFrame * (m_InterruptTime + 1));
        KeSetTimer (&m_IsrTimer, NextTime, &m_IsrFakeDpc);
    }

    InterlockedDecrement(&m_DpcActive);

}


void CHardwareSimulation::SetData(PVOID data, ULONG dataLength)
{
    KIRQL irql;
    BOOLEAN shouldWrite = FALSE;
    PUCHAR temporaryBuffer = NULL;
    ULONG width = 0;
    ULONG height = 0;
    ULONG imageSize = 0;
    ULONG outputBytesPerPixel = 0;
    LARGE_INTEGER now = {};
    ULONG rejectReason = kSetDataRejectNone;

    KeAcquireSpinLock(&m_FrameLock, &irql);
    if (m_HardwareState != HardwareRunning) {
        rejectReason = kSetDataRejectNotRunning;
    } else if (!m_TemporaryBuffer) {
        rejectReason = kSetDataRejectNoBuffer;
    } else if (!m_ImageSynth) {
        rejectReason = kSetDataRejectNoSynth;
    } else {
        shouldWrite = TRUE;
        temporaryBuffer = m_TemporaryBuffer;
        width = m_Width;
        height = m_Height;
        imageSize = m_ImageSize;
        outputBytesPerPixel = static_cast<ULONG>(m_ImageSynth->GetBytesPerPixel());
        InterlockedIncrement(&m_FrameWriteActive);
    }
    m_LastSetDataLength = dataLength;
    KeReleaseSpinLock(&m_FrameLock, irql);

    if (!shouldWrite || !temporaryBuffer || outputBytesPerPixel == 0) {
        InterlockedIncrement(reinterpret_cast<volatile LONG*>(&m_SetDataRejectedCount));
        m_LastSetDataReason = rejectReason;
        return;
    }

    const ULONGLONG requiredSourceLength64 = static_cast<ULONGLONG>(width) * static_cast<ULONGLONG>(height) * 3ull;
    if (requiredSourceLength64 > MAXULONG) {
        InterlockedIncrement(reinterpret_cast<volatile LONG*>(&m_SetDataRejectedCount));
        m_LastSetDataReason = kSetDataRejectBadGeometry;
        InterlockedDecrement(&m_FrameWriteActive);
        return;
    }

    const ULONG requiredSourceLength = static_cast<ULONG>(requiredSourceLength64);

	if (dataLength < requiredSourceLength)
	{
        InterlockedIncrement(reinterpret_cast<volatile LONG*>(&m_SetDataRejectedCount));
        m_LastSetDataReason = kSetDataRejectShortSource;
        InterlockedDecrement(&m_FrameWriteActive);
		return;
	}

    KeQuerySystemTimePrecise(&now);

    static volatile LONG s_hwFrameSequence = 0;
    LONG seq = _InterlockedIncrement(&s_hwFrameSequence);

    if (outputBytesPerPixel == 2) {
        ConvertRgb24ToYuy2Frame(
            temporaryBuffer,
            imageSize,
            reinterpret_cast<const UCHAR*>(data),
            dataLength,
            width,
            height);
    } else {
	    for (ULONG y = 0; y < height; y++)
	    {
		    PUCHAR buffer = temporaryBuffer + ((width * 3) * (height - 1 - y));
		    PUCHAR dataLine = (PUCHAR)(data) + ((width * 3) * y);

		    RtlCopyMemory(buffer, dataLine, width * 3);
	    }
    }

    KeAcquireSpinLock(&m_FrameLock, &irql);
    if (m_HardwareState == HardwareRunning &&
        m_ClientConnected &&
        m_TemporaryBuffer == temporaryBuffer) {
        m_LastFrameTime = now;
    }
    KeReleaseSpinLock(&m_FrameLock, irql);
    InterlockedIncrement(reinterpret_cast<volatile LONG*>(&m_SetDataAcceptedCount));
    m_LastSetDataReason = kSetDataRejectNone;
    InterlockedDecrement(&m_FrameWriteActive);

    if (seq <= 3 || seq % 30 == 0) {
        DbgPrint("[avshws] HwSim::SetData frame=%ld bytes=%lu active=%ld irql=%lu\n", seq, dataLength, InterlockedCompareExchange(&m_FrameWriteActive, 0, 0), (ULONG)KeGetCurrentIrql());
    }
}

void CHardwareSimulation::SetClientConnected(BOOLEAN connected)
{
    KIRQL irql;
    KeAcquireSpinLock(&m_FrameLock, &irql);
    m_ClientConnected = connected;
    if (connected) {
        KeQuerySystemTimePrecise(&m_LastFrameTime);
    } else {
        m_LastFrameTime.QuadPart = 0;
    }
    KeReleaseSpinLock(&m_FrameLock, irql);
    DbgPrint("[avshws] HwSim::SetClientConnected connected=%lu irql=%lu\n", (ULONG)connected, (ULONG)KeGetCurrentIrql());
}

BOOLEAN CHardwareSimulation::IsClientConnected()
{
    KIRQL irql;
    BOOLEAN connected = FALSE;
    KeAcquireSpinLock(&m_FrameLock, &irql);
    connected = m_ClientConnected;
    KeReleaseSpinLock(&m_FrameLock, irql);
    return connected;
}

void CHardwareSimulation::NotifyCameraState(BOOLEAN isRunning)
{
    PKEVENT clientRequestEventObject = NULL;
    BOOLEAN clientConnected = FALSE;
    KIRQL irql;

    DbgPrint("[avshws] HwSim::NotifyCameraState running=%lu connected=%lu irql=%lu\n", (ULONG)isRunning, (ULONG)IsClientConnected(), (ULONG)KeGetCurrentIrql());

    KeAcquireSpinLock(&m_FrameLock, &irql);
    clientRequestEventObject = m_ClientRequestEventObject;
    clientConnected = m_ClientConnected;
    KeReleaseSpinLock(&m_FrameLock, irql);

    if (isRunning) {
        if (clientRequestEventObject && !clientConnected) {
            KeSetEvent(clientRequestEventObject, IO_NO_INCREMENT, FALSE);
        }
    } else if (clientRequestEventObject) {
        KeClearEvent(clientRequestEventObject);
    }
}

void CHardwareSimulation::QueryStatus(_Out_ PVIRTUACAM_DRIVER_STATUS status)
{
    if (!status) {
        return;
    }

    KIRQL irql;
    KeAcquireSpinLock(&m_FrameLock, &irql);
    status->HardwareState = static_cast<ULONG>(m_HardwareState);
    status->ClientConnected = static_cast<ULONG>(m_ClientConnected);
    status->Width = m_Width;
    status->Height = m_Height;
    status->ImageSize = m_ImageSize;
    status->InterruptTime = m_InterruptTime;
    status->LastFrameTime100ns = static_cast<ULONGLONG>(m_LastFrameTime.QuadPart);
    KeReleaseSpinLock(&m_FrameLock, irql);

    KeAcquireSpinLock(&m_ListLock, &irql);
    status->ScatterGatherMappingsQueued = m_ScatterGatherMappingsQueued;
    status->ScatterGatherBytesQueued = m_ScatterGatherBytesQueued;
    status->NumMappingsCompleted = m_NumMappingsCompleted;
    status->NumFramesSkipped = m_NumFramesSkipped;
    status->LastCompletedDelta = m_LastCompletedDelta;
    KeReleaseSpinLock(&m_ListLock, irql);

    status->LastFillStatus = m_LastFillStatus;
    status->LastFillStride = m_LastFillStride;
    status->LastFillWidthBytes = m_LastFillWidthBytes;
    status->LastFillRequiredBytes = m_LastFillRequiredBytes;
    status->LastFillByteCount = m_LastFillByteCount;
    status->LastFillBufferRemaining = m_LastFillBufferRemaining;
    status->LastSetDataLength = m_LastSetDataLength;
    status->SetDataAcceptedCount = m_SetDataAcceptedCount;
    status->SetDataRejectedCount = m_SetDataRejectedCount;
    status->LastSetDataReason = m_LastSetDataReason;
}
